# Shell variables
# Generated by 'wal'
wallpaper='/home/msnkr/Pictures/EzOfjEBVUAAYYn7.jpg'

# Special
background='#0C012D'
foreground='#edc3f5'
cursor='#edc3f5'

# Colors
color0='#0C012D'
color1='#B529F5'
color2='#D60CEC'
color3='#C72CFB'
color4='#AA49D7'
color5='#DE5FF9'
color6='#D1D3BA'
color7='#edc3f5'
color8='#a588ab'
color9='#B529F5'
color10='#D60CEC'
color11='#C72CFB'
color12='#AA49D7'
color13='#DE5FF9'
color14='#D1D3BA'
color15='#edc3f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
