--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/msnkr/Pictures/EzOfjEBVUAAYYn7.jpg"

-- Special
background="#0C012D"
foreground="#edc3f5"
cursor="#edc3f5"

-- Colors
color0="#0C012D"
color1="#B529F5"
color2="#D60CEC"
color3="#C72CFB"
color4="#AA49D7"
color5="#DE5FF9"
color6="#D1D3BA"
color7="#edc3f5"
color8="#a588ab"
color9="#B529F5"
color10="#D60CEC"
color11="#C72CFB"
color12="#AA49D7"
color13="#DE5FF9"
color14="#D1D3BA"
color15="#edc3f5"
